/**
 * ecommerce-taxonomy.ts
 *
 * The full taxonomy of e-commerce UI elements, with generic candidate
 * selector chains for each intent.
 *
 * Design principles:
 *  - Generic first: works across Shopify, Magento, WooCommerce, custom React
 *  - Stable first: data-testid > id > aria > semantic class > generic tag
 *  - No site-specific selectors here — those come from the consensus scorer
 *
 * Each intent maps to:
 *   { candidates: string[], pageTypes: PageTypeKey[], verifyAs: VerifyMode }
 *
 * VerifyMode controls how content-verifier checks the element:
 *   'text'   → must have non-trivial text content
 *   'price'  → text must parse as a number
 *   'image'  → must contain or be an <img> with a real src
 *   'exists' → just needs to exist in DOM
 *   'count'  → parent must contain ≥ 2 child items
 */

import type { PageTypeKey } from '../shared-types'

export type VerifyMode = 'text' | 'price' | 'image' | 'exists' | 'count'

export interface TaxonomyEntry {
  candidates: string[]
  pageTypes: PageTypeKey[]
  verifyAs: VerifyMode
  description: string
}

export type Taxonomy = Record<string, TaxonomyEntry>

// ── Global elements (present on all / most pages) ─────────────────────────────

const GLOBAL: Taxonomy = {
  header: {
    description: 'Site header wrapper',
    pageTypes: ['home', 'product', 'category', 'cart', 'search', 'other'],
    verifyAs: 'exists',
    candidates: [
      'header[role="banner"]',
      'header',
      '[class*="header"]:not([class*="sub"])',
      '[id*="header"]',
      '[class*="site-header"]',
      '[class*="siteHeader"]',
      '[class*="page-header"]',
    ],
  },
  searchBar: {
    description: 'Site-wide search input',
    pageTypes: ['home', 'product', 'category', 'cart', 'search', 'other'],
    verifyAs: 'exists',
    candidates: [
      'input[type="search"]',
      'input[placeholder*="search" i]',
      'input[placeholder*="find" i]',
      'input[aria-label*="search" i]',
      '[data-testid*="search"] input',
      '[class*="search-input"]',
      '[class*="searchInput"]',
      '[class*="search-bar"] input',
      'form[role="search"] input',
    ],
  },
  cartBadge: {
    description: 'Cart icon / item count badge in header',
    pageTypes: ['home', 'product', 'category', 'cart', 'search', 'other'],
    verifyAs: 'text',
    candidates: [
      '[data-testid*="cart-count"]',
      '[data-testid*="cart-badge"]',
      '[aria-label*="cart" i]',
      'a[href*="cart"] [class*="count"]',
      'a[href*="cart"] [class*="badge"]',
      '[class*="cart-count"]',
      '[class*="cartCount"]',
      '[class*="cart-badge"]',
      '[class*="cartBadge"]',
      '[class*="cart-icon"]',
    ],
  },
  navCategories: {
    description: 'Main navigation category links',
    pageTypes: ['home', 'product', 'category', 'search', 'other'],
    verifyAs: 'count',
    candidates: [
      'nav[aria-label*="main" i] a',
      'nav[role="navigation"] a',
      '[class*="main-nav"] a',
      '[class*="mainNav"] a',
      '[class*="primary-nav"] a',
      '[class*="nav-menu"] a',
      '[class*="navMenu"] a',
      'header nav a',
      '[class*="mega-menu"] a',
    ],
  },
  breadcrumb: {
    description: 'Breadcrumb navigation trail',
    pageTypes: ['product', 'category', 'search', 'other'],
    verifyAs: 'count',
    candidates: [
      '[aria-label="breadcrumb"] a',
      '[aria-label="Breadcrumb"] a',
      'nav[aria-label*="breadcrumb" i] a',
      '[class*="breadcrumb"] a',
      '[class*="breadcrumbs"] a',
      '[class*="BreadCrumb"] a',
      '[itemtype*="BreadcrumbList"] a',
      'ol[class*="breadcrumb"] li',
    ],
  },
  userAccount: {
    description: 'Account / login link or menu',
    pageTypes: ['home', 'product', 'category', 'cart', 'other'],
    verifyAs: 'exists',
    candidates: [
      '[data-testid*="account"]',
      '[data-testid*="user"]',
      'a[href*="account"]',
      'a[href*="login"]',
      'a[href*="profile"]',
      '[aria-label*="account" i]',
      '[class*="user-account"]',
      '[class*="userAccount"]',
      '[class*="account-menu"]',
    ],
  },
  footer: {
    description: 'Site footer',
    pageTypes: ['home', 'product', 'category', 'cart', 'search', 'other'],
    verifyAs: 'exists',
    candidates: [
      'footer[role="contentinfo"]',
      'footer',
      '[class*="site-footer"]',
      '[class*="siteFooter"]',
      '[id="footer"]',
    ],
  },
}

// ── Product Detail Page (PDP) ─────────────────────────────────────────────────

const PDP: Taxonomy = {
  productTitle: {
    description: 'Main product name / title',
    pageTypes: ['product'],
    verifyAs: 'text',
    candidates: [
      '[data-testid="product-title"]',
      '[data-testid="product-name"]',
      'h1[class*="pdp"]',
      'h1[class*="product"]',
      'h1[class*="title"]',
      'h1[class*="name"]',
      '[class*="product-title"]',
      '[class*="productTitle"]',
      '[class*="product-name"]',
      '[class*="productName"]',
      '[itemProp="name"]',
      'h1',
    ],
  },
  price: {
    description: 'Current selling price',
    pageTypes: ['product'],
    verifyAs: 'price',
    candidates: [
      '[data-testid="price"]',
      '[data-testid="selling-price"]',
      '[data-testid="product-price"]',
      '[class*="selling-price"]',
      '[class*="sellingPrice"]',
      '[class*="sale-price"]',
      '[class*="salePrice"]',
      '[class*="current-price"]',
      '[class*="currentPrice"]',
      '[class*="final-price"]',
      '[class*="finalPrice"]',
      '[class*="price-now"]',
      '[class*="price--sale"]',
      '[class*="pdp-price"]',
      '.price-current',
      '[itemProp="price"]',
      '[class*="offer-price"]',
      '[class*="offerPrice"]',
    ],
  },
  originalPrice: {
    description: 'Original / MRP / struck-through price',
    pageTypes: ['product'],
    verifyAs: 'price',
    candidates: [
      '[data-testid="original-price"]',
      '[data-testid="compare-price"]',
      '[class*="original-price"]',
      '[class*="originalPrice"]',
      '[class*="compare-price"]',
      '[class*="comparePrice"]',
      '[class*="mrp"]',
      '[class*="was-price"]',
      '[class*="wasPrice"]',
      '[class*="strike-price"]',
      '[class*="strikePrice"]',
      'del[class*="price"]',
      's[class*="price"]',
      'del',
      's',
    ],
  },
  discountBadge: {
    description: 'Discount percentage or savings badge',
    pageTypes: ['product'],
    verifyAs: 'text',
    candidates: [
      '[data-testid*="discount"]',
      '[class*="discount-badge"]',
      '[class*="discountBadge"]',
      '[class*="savings-badge"]',
      '[class*="sale-badge"]',
      '[class*="saleBadge"]',
      '[class*="off-badge"]',
      '[class*="percent-off"]',
      '[class*="discount-percent"]',
      '[class*="deal-badge"]',
    ],
  },
  stockStatus: {
    description: 'In stock / out of stock indicator',
    pageTypes: ['product'],
    verifyAs: 'text',
    candidates: [
      '[data-testid*="stock"]',
      '[data-testid*="availability"]',
      '[class*="stock-status"]',
      '[class*="stockStatus"]',
      '[class*="availability"]',
      '[class*="in-stock"]',
      '[class*="out-of-stock"]',
      '[itemProp="availability"]',
      '[aria-label*="stock" i]',
      '[aria-label*="available" i]',
    ],
  },
  addToCart: {
    description: 'Primary add-to-cart button',
    pageTypes: ['product'],
    verifyAs: 'exists',
    candidates: [
      '[data-testid="add-to-cart"]',
      'button[class*="add-to-cart"]',
      'button[class*="addToCart"]',
      'button[class*="add_to_cart"]',
      'button[id*="add-to-cart"]',
      '[aria-label*="add to cart" i]',
      '[aria-label*="add to bag" i]',
      'button[class*="atc"]',
      'button[name="add"]',
      'input[name="add"][type="submit"]',
      // Generic fallbacks: large primary buttons on product pages
      'form button[type="submit"]',
    ],
  },
  buyNow: {
    description: 'Buy now / instant checkout button',
    pageTypes: ['product'],
    verifyAs: 'exists',
    candidates: [
      '[data-testid="buy-now"]',
      'button[class*="buy-now"]',
      'button[class*="buyNow"]',
      'button[class*="buy_now"]',
      '[aria-label*="buy now" i]',
      'button[class*="checkout-now"]',
      'a[class*="buy-now"]',
    ],
  },
  quantitySelector: {
    description: 'Product quantity input or stepper',
    pageTypes: ['product'],
    verifyAs: 'exists',
    candidates: [
      '[data-testid="quantity"]',
      'input[type="number"][class*="qty"]',
      'input[type="number"][class*="quantity"]',
      'input[name="quantity"]',
      '[class*="quantity-selector"]',
      '[class*="quantitySelector"]',
      '[class*="qty-selector"]',
      '[class*="quantity-stepper"]',
      '[class*="quantity-input"]',
    ],
  },
  sizeSelector: {
    description: 'Size / dimension variant picker',
    pageTypes: ['product'],
    verifyAs: 'count',
    candidates: [
      '[data-testid="size-option"]',
      '[data-testid="size-selector"]',
      '.size-selector button',
      '.size-options button',
      '[class*="size-selector"] button',
      '[class*="sizeSelector"] button',
      '[class*="size-picker"] button',
      '[class*="size-option"]',
      '[class*="dimension-option"]',
      '[class*="variant-size"] button',
      '[class*="variantSelector"] [role="radio"]',
      '[aria-label*="size" i]',
    ],
  },
  colorSelector: {
    description: 'Color / finish variant picker',
    pageTypes: ['product'],
    verifyAs: 'count',
    candidates: [
      '[data-testid="color-option"]',
      '[data-testid="color-selector"]',
      '[class*="color-selector"] button',
      '[class*="colorSelector"] button',
      '[class*="color-picker"] button',
      '[class*="color-swatch"]',
      '[class*="colorSwatch"]',
      '[class*="variant-color"]',
      '[aria-label*="color" i]',
    ],
  },
  materialSelector: {
    description: 'Material / fabric variant picker',
    pageTypes: ['product'],
    verifyAs: 'count',
    candidates: [
      '[data-testid="material-option"]',
      '[class*="material-selector"] button',
      '[class*="fabric-selector"] button',
      '[class*="variant-material"]',
      '[aria-label*="material" i]',
      '[aria-label*="fabric" i]',
    ],
  },
  productImages: {
    description: 'Main product image gallery container',
    pageTypes: ['product'],
    verifyAs: 'image',
    candidates: [
      '[data-testid="product-images"]',
      '[data-testid="image-gallery"]',
      '[data-testid="gallery"]',
      '[class*="product-images"]',
      '[class*="productImages"]',
      '[class*="product-gallery"]',
      '[class*="productGallery"]',
      '[class*="image-gallery"]',
      '[class*="imageGallery"]',
      '[class*="pdp-images"]',
      '[class*="pdpImages"]',
      '[class*="pdp-image"]',
      '[class*="main-image"]',
      '[class*="mainImage"]',
      '[class*="hero-image"]',
      '.swiper-container',
      '.slick-slider',
      '[class*="carousel"]',
      '[role="img"]',
      'figure',
    ],
  },
  thumbnails: {
    description: 'Image thumbnail strip / dot indicators',
    pageTypes: ['product'],
    verifyAs: 'count',
    candidates: [
      '[data-testid="thumbnails"]',
      '[class*="thumbnail"] img',
      '[class*="thumbnails"] img',
      '[class*="image-thumb"]',
      '[class*="product-thumb"]',
      '.swiper-slide img',
      '[class*="carousel-thumb"]',
      '[class*="gallery-dot"]',
    ],
  },
  specsSection: {
    description: 'Product specifications section wrapper',
    pageTypes: ['product'],
    verifyAs: 'text',
    candidates: [
      '#specifications',
      '#product-specifications',
      '[data-section="specifications"]',
      '[data-tab="specifications"]',
      '[class*="specification"]',
      '[class*="specifications"]',
      '[class*="product-details"]',
      '[class*="productDetails"]',
      '[class*="product-specs"]',
      '[class*="productSpecs"]',
      '[class*="tech-specs"]',
      '[class*="techSpecs"]',
    ],
  },
  specsTable: {
    description: 'Specification key-value table',
    pageTypes: ['product'],
    verifyAs: 'exists',
    candidates: [
      '[class*="specifications"] table',
      '[class*="spec-table"]',
      '[class*="specTable"]',
      '[class*="product-details"] table',
      '[class*="product-specs"] table',
      'table[class*="spec"]',
      'dl[class*="spec"]',
      'dl[class*="detail"]',
      '[class*="attribute-table"]',
    ],
  },
  highlights: {
    description: 'Key features / highlights bullet list',
    pageTypes: ['product'],
    verifyAs: 'count',
    candidates: [
      '[data-testid="highlights"]',
      '.product-highlights li',
      '.key-features li',
      '[class*="highlight"] li',
      '[class*="highlights"] li',
      '[class*="feature"] li',
      '[class*="features"] li',
      '[class*="benefit"] li',
      '[class*="benefits"] li',
      '[class*="usp"] li',
      '[class*="why-buy"] li',
      '[class*="selling-point"] li',
    ],
  },
  rating: {
    description: 'Aggregate star rating value',
    pageTypes: ['product'],
    verifyAs: 'text',
    candidates: [
      '[data-testid="rating"]',
      '[data-testid="rating-value"]',
      '[class*="rating-value"]',
      '[class*="ratingValue"]',
      '[class*="star-rating"]',
      '[class*="review-score"]',
      '[aria-label*="rating" i]',
      '[aria-label*="stars" i]',
      '[itemProp="ratingValue"]',
    ],
  },
  reviewCount: {
    description: 'Total number of reviews / ratings',
    pageTypes: ['product'],
    verifyAs: 'text',
    candidates: [
      '[data-testid="review-count"]',
      '[class*="review-count"]',
      '[class*="reviewCount"]',
      '[class*="ratings-count"]',
      '[class*="ratingsCount"]',
      '[class*="total-reviews"]',
      '[class*="totalReviews"]',
      '[class*="num-reviews"]',
      '[itemProp="reviewCount"]',
    ],
  },
  reviewSection: {
    description: 'Customer reviews section',
    pageTypes: ['product'],
    verifyAs: 'exists',
    candidates: [
      '#reviews',
      '#customer-reviews',
      '[data-section="reviews"]',
      '.reviews-section',
      '[class*="review-section"]',
      '[class*="reviewSection"]',
      '[class*="customer-reviews"]',
      '[class*="product-reviews"]',
    ],
  },
  trialBanner: {
    description: 'Trial period / sleep trial badge',
    pageTypes: ['product'],
    verifyAs: 'text',
    candidates: [
      '[data-testid="trial-info"]',
      '.trial-banner',
      '[class*="trial-period"]',
      '[class*="trialPeriod"]',
      '[class*="night-trial"]',
      '[class*="free-trial"]',
      '[class*="trial-badge"]',
      '[class*="sleep-trial"]',
    ],
  },
  warrantyInfo: {
    description: 'Warranty / guarantee information',
    pageTypes: ['product'],
    verifyAs: 'text',
    candidates: [
      '[data-testid="warranty"]',
      '.warranty',
      '[class*="warranty"]',
      '[class*="guarantee"]',
      '[class*="warranty-badge"]',
      '[aria-label*="warranty" i]',
    ],
  },
  emiInfo: {
    description: 'EMI / instalment payment options',
    pageTypes: ['product'],
    verifyAs: 'exists',
    candidates: [
      '[data-testid="emi"]',
      '.emi-options',
      '[class*="emi-options"]',
      '[class*="emiOptions"]',
      '[class*="installment"]',
      '[class*="payment-options"]',
      '[class*="paymentOptions"]',
      '[class*="buy-on-emi"]',
    ],
  },
  deliveryInfo: {
    description: 'Delivery / shipping estimate',
    pageTypes: ['product'],
    verifyAs: 'text',
    candidates: [
      '[data-testid="delivery"]',
      '[data-testid="shipping"]',
      '[class*="delivery-info"]',
      '[class*="deliveryInfo"]',
      '[class*="shipping-info"]',
      '[class*="shipment"]',
      '[class*="delivery-estimate"]',
      '[class*="free-delivery"]',
      '[class*="delivery-date"]',
      '[class*="expected-delivery"]',
    ],
  },
  relatedProducts: {
    description: 'Related / similar / recommended products section',
    pageTypes: ['product'],
    verifyAs: 'count',
    candidates: [
      '[data-testid="related-products"]',
      '[class*="related-products"]',
      '[class*="relatedProducts"]',
      '[class*="similar-products"]',
      '[class*="similarProducts"]',
      '[class*="you-may-like"]',
      '[class*="youMayLike"]',
      '[class*="also-bought"]',
      '[class*="recommended"]',
      '[class*="frequently-bought"]',
    ],
  },
  recentlyViewed: {
    description: 'Recently viewed products',
    pageTypes: ['product', 'home'],
    verifyAs: 'count',
    candidates: [
      '[data-testid="recently-viewed"]',
      '[class*="recently-viewed"]',
      '[class*="recentlyViewed"]',
      '[class*="recent-products"]',
      '[class*="browsing-history"]',
    ],
  },
}

// ── Category / Listing Page (PLP) ─────────────────────────────────────────────

const PLP: Taxonomy = {
  categoryTitle: {
    description: 'Category / collection page heading',
    pageTypes: ['category', 'search'],
    verifyAs: 'text',
    candidates: [
      'h1[class*="category"]',
      'h1[class*="collection"]',
      'h1[class*="listing"]',
      '[class*="category-title"]',
      '[class*="categoryTitle"]',
      '[class*="page-title"]',
      '[class*="pageTitle"]',
      'h1',
    ],
  },
  productCards: {
    description: 'Individual product card containers in a listing',
    pageTypes: ['category', 'search'],
    verifyAs: 'count',
    candidates: [
      '[data-testid="product-card"]',
      '[data-testid="product-item"]',
      '.product-card',
      '.product-item',
      '[class*="product-card"]',
      '[class*="productCard"]',
      '[class*="product-item"]',
      '[class*="productItem"]',
      '[class*="card-item"]',
      '[class*="cardItem"]',
      'li[class*="product"]',
      '[class*="collection-item"]',
      '[class*="grid-item"][class*="product"]',
    ],
  },
  productCardName: {
    description: 'Product name within a listing card',
    pageTypes: ['category', 'search'],
    verifyAs: 'text',
    candidates: [
      '[class*="product-card"] [class*="name"]',
      '[class*="product-card"] [class*="title"]',
      '[class*="product-card"] h2',
      '[class*="product-card"] h3',
      '[class*="product-card"] h4',
      '[class*="productCard"] [class*="name"]',
      '[class*="card-title"]',
      '[class*="cardTitle"]',
    ],
  },
  productCardPrice: {
    description: 'Product price within a listing card',
    pageTypes: ['category', 'search'],
    verifyAs: 'price',
    candidates: [
      '[class*="product-card"] [class*="price"]',
      '[class*="productCard"] [class*="price"]',
      '[class*="product-item"] [class*="price"]',
      '[class*="card-price"]',
      '[class*="cardPrice"]',
      '[class*="listing-price"]',
    ],
  },
  productCardRating: {
    description: 'Product rating within a listing card',
    pageTypes: ['category', 'search'],
    verifyAs: 'text',
    candidates: [
      '[class*="product-card"] [class*="rating"]',
      '[class*="productCard"] [class*="rating"]',
      '[class*="product-item"] [class*="rating"]',
      '[class*="card-rating"]',
      '[class*="star-rating"]',
    ],
  },
  productCardImage: {
    description: 'Product image within a listing card',
    pageTypes: ['category', 'search'],
    verifyAs: 'image',
    candidates: [
      '[class*="product-card"] img',
      '[class*="productCard"] img',
      '[class*="product-item"] img',
      '[class*="card-image"] img',
      '[class*="product-image"]',
      '[class*="thumbnail-image"]',
    ],
  },
  filterSidebar: {
    description: 'Filter / facet sidebar panel',
    pageTypes: ['category', 'search'],
    verifyAs: 'exists',
    candidates: [
      '[data-testid="filters"]',
      '[data-testid="filter-sidebar"]',
      '.filter-sidebar',
      '.filters',
      '[class*="filter-sidebar"]',
      '[class*="filterSidebar"]',
      '[class*="facet-sidebar"]',
      '[class*="facetSidebar"]',
      '[class*="refinements"]',
      'aside[class*="filter"]',
    ],
  },
  activeFilters: {
    description: 'Currently active / applied filters',
    pageTypes: ['category', 'search'],
    verifyAs: 'count',
    candidates: [
      '[class*="active-filters"]',
      '[class*="activeFilters"]',
      '[class*="applied-filters"]',
      '[class*="appliedFilters"]',
      '[class*="selected-filters"]',
      '[class*="filter-tags"]',
      '[class*="filter-chips"]',
    ],
  },
  sortDropdown: {
    description: 'Sort by / order by dropdown',
    pageTypes: ['category', 'search'],
    verifyAs: 'exists',
    candidates: [
      '[data-testid="sort"]',
      'select[class*="sort"]',
      '[class*="sort-by"]',
      '[class*="sortBy"]',
      '[class*="sort-dropdown"]',
      '[class*="sort-select"]',
      'button[class*="sort"]',
      '[aria-label*="sort" i]',
    ],
  },
  pagination: {
    description: 'Page navigation / load more controls',
    pageTypes: ['category', 'search'],
    verifyAs: 'exists',
    candidates: [
      '[aria-label="pagination"]',
      '[class*="pagination"]',
      '[class*="load-more"]',
      '[class*="loadMore"]',
      'button[class*="show-more"]',
      'nav[class*="pagination"]',
      '[class*="page-navigation"]',
    ],
  },
  productCount: {
    description: 'Total number of products shown',
    pageTypes: ['category', 'search'],
    verifyAs: 'text',
    candidates: [
      '[data-testid="product-count"]',
      '[class*="product-count"]',
      '[class*="productCount"]',
      '[class*="results-count"]',
      '[class*="item-count"]',
      '[class*="total-results"]',
      '[class*="showing-results"]',
    ],
  },
}

// ── Cart page ─────────────────────────────────────────────────────────────────

const CART: Taxonomy = {
  cartItems: {
    description: 'Cart line item containers',
    pageTypes: ['cart'],
    verifyAs: 'count',
    candidates: [
      '[data-testid="cart-item"]',
      '[class*="cart-item"]',
      '[class*="cartItem"]',
      '[class*="cart-line"]',
      '[class*="line-item"]',
      '[class*="lineItem"]',
      '[class*="cart-product"]',
      'tr[class*="cart"]',
    ],
  },
  cartItemName: {
    description: 'Product name within a cart line item',
    pageTypes: ['cart'],
    verifyAs: 'text',
    candidates: [
      '[class*="cart-item"] [class*="name"]',
      '[class*="cart-item"] [class*="title"]',
      '[class*="cartItem"] [class*="name"]',
      '[class*="cart-item-title"]',
      '[class*="line-item-title"]',
    ],
  },
  cartItemQty: {
    description: 'Quantity input within a cart line item',
    pageTypes: ['cart'],
    verifyAs: 'exists',
    candidates: [
      '[class*="cart-item"] input[type="number"]',
      '[class*="cart-item"] [class*="qty"]',
      '[class*="cart-quantity"]',
      '[class*="cartQuantity"]',
      '[class*="item-quantity"]',
    ],
  },
  cartTotal: {
    description: 'Cart total / grand total amount',
    pageTypes: ['cart'],
    verifyAs: 'price',
    candidates: [
      '[data-testid="cart-total"]',
      '[class*="cart-total"]',
      '[class*="cartTotal"]',
      '[class*="order-total"]',
      '[class*="grand-total"]',
      '[class*="grandTotal"]',
      '[class*="subtotal"]',
    ],
  },
  proceedToCheckout: {
    description: 'Checkout / proceed to pay button',
    pageTypes: ['cart'],
    verifyAs: 'exists',
    candidates: [
      '[data-testid="checkout"]',
      'button[class*="checkout"]',
      'a[class*="checkout"]',
      'button[class*="proceed"]',
      '[class*="proceed-to-checkout"]',
      '[class*="proceedToCheckout"]',
      '[aria-label*="checkout" i]',
      'button[name="checkout"]',
    ],
  },
  couponInput: {
    description: 'Coupon / promo code input',
    pageTypes: ['cart'],
    verifyAs: 'exists',
    candidates: [
      'input[name="coupon"]',
      'input[placeholder*="coupon" i]',
      'input[placeholder*="promo" i]',
      'input[placeholder*="discount" i]',
      '[class*="coupon-input"]',
      '[class*="couponInput"]',
      '[class*="promo-code"] input',
      '[class*="discount-code"] input',
    ],
  },
}

// ── Merged full taxonomy ──────────────────────────────────────────────────────

export const ECOMMERCE_TAXONOMY: Taxonomy = {
  ...GLOBAL,
  ...PDP,
  ...PLP,
  ...CART,
}

/** Intents that belong to each page type group (for coverage calculation) */
export const TAXONOMY_GROUPS = {
  global:  Object.keys(GLOBAL),
  pdp:     Object.keys(PDP),
  plp:     Object.keys(PLP),
  cart:    Object.keys(CART),
}

/** All unique intents */
export const ALL_INTENTS = Object.keys(ECOMMERCE_TAXONOMY)
